config/routes.rb
Rails.application.routes.draw do
  resources :real_states, only: [ :index, :show ]

  devise_for :users

  namespace :admin do
    resources :users
    resources :buildings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
      resources :common_rooms, only: [ :new, :create, :show, :edit, :update, :destroy ]
    end
    resources :units, only: [ :new, :create, :show, :edit, :update, :destroy ] # TODO mover al resource building
    resources :real_states, only: [ :new, :create, :index, :show, :edit, :update, :destroy ]
  end



  resources :user_profile, only: [ :show, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'home#home'

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/real_state.rb
class RealState < Property
  after_initialize :set_default_type

  belongs_to :owner, class_name: 'User', optional: true
  belongs_to :tenant, class_name: 'User', optional: true
  default_scope { where(type: 'RealState') }

  validates :address, presence: true
  validate :unique_number_when_building_id_nil

  def unique_number_when_building_id_nil
    return if building_id.present?
  
    if self.class.where(number: number, building_id: nil).where.not(id: id).exists?
      errors.add(:number, I18n.t('activerecord.errors.models.real_state.attribute.number.taken'))
    end
  end
  
  def set_default_type
    self.type ||= 'RealState'
  end
end

app/controllers/admin/real_states_controller.rb
class Admin::RealStatesController < ApplicationController
  include UserRoleValidation

  before_action :authenticate_user!
  before_action :is_admin?

  include UserRoleValidation
  def new
    @real_state = RealState.new
    load_info
  end

  def create
    @real_state = RealState.new(real_state_params)

    validate_users_and_roles!(owner_id: @real_state.owner_id, tenant_id: @real_state.tenant_id)

    if @real_state.save
      redirect_to admin_real_state_path(@real_state), notice: "La propiedad #{@real_state.number} ha sido creada exitosamente."
    else
      load_info
      render :new, status: :unprocessable_entity
    end
  rescue  ActiveRecord::RecordNotFound => e
    @real_state = RealState.new(real_state_params)
    @real_state.errors.add(:base, e.message)
    load_info
    render :new, status: :unprocessable_entity
  end

  def index
    @real_states = real_state_search_service
  end

  def show
    @real_state = RealState.find(params[:id])
  end

  def edit
    load_info

    @real_state = RealState.find(params[:id])
  end

  def update
    @real_state = RealState.find(params[:id])
    validate_users_and_roles!(owner_id: real_state_params[:owner_id], tenant_id: real_state_params[:tenant_id])
    if @real_state.update(real_state_params)
      redirect_to admin_real_state_path(@real_state), notice: "La propiedad #{@real_state.number} ha sido actualizada exitosamente."
    else
      load_info
      render :edit, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound => e
    @real_state = RealState.new(real_state_params)
    @real_state.errors.add(:base, e.message)
    load_info
    render :new, status: :unprocessable_entity
  end

  def destroy
    @real_state = RealState.find(params[:id])

    if @real_state.destroy
      redirect_to admin_real_states_path, notice: "La propiedad #{@real_state.number} ha sido eliminada exitosamente."
    else
      render :index, alert: "No se pudo eliminar la propiedad #{@real_state.number}."
    end
  end

  private

  def real_state_search_service
    Admin::SearchRealStatesService.new(query: params[:query], page: params[:page]).call
  end

  def load_info
    @owners = User.with_role(:owner)
    @tenants = User.with_role(:tenant)
  end

  def real_state_params
    params.require(:real_state).permit(:number, :owner_id, :tenant_id, :address)
  end

  def is_admin?
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: 'Acceso denegado.'
    end
  end
end

app/helpers/real_states_helper.rb
module RealStatesHelper
end

app/views/admin/real_states/_real_state_card.html.erb
<div class="max-w-sm p-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700">
  <a href="<%= admin_real_state_path(real_state.id) %>" class='text-nowrap overflow-hidden'>
      <p id='real-state-number-<%= real_state.number %>'class="mb-2 text-2xl font-bold tracking-tight text-stone-700 dark:text-white truncate"><%= real_state.number %></p>
  </a>

  <p class="truncate mb-3 font-normal text-stone-700 dark:text-stone-400"><%= real_state.address %></p>

  <div class="flex justify-between items-center">
    <a href="<%= admin_real_state_path(real_state.id) %>" id='show-real-state-<%= real_state.number %>' class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Ver más
      <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    </a>

    <% if current_user.has_role? :admin %>
      <button data-modal-target="<%= real_state.number %>" data-modal-toggle="<%= real_state.number %>" class=" block text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" type="button", id='delete-real-state-<%= real_state.number %>-modal'>
        <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
        </svg>
      </button>

      <div id="<%= real_state.number %>" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
        <div class="relative p-4 w-full max-w-md max-h-full">
          <div class="relative bg-white rounded-lg shadow-sm dark:bg-gray-700">
            <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="<%= real_state.number %>">
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
              </svg>
              <span class="sr-only">Cerrar modal</span>
            </button>
            <div class="p-4 md:p-5 text-center">
              <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
              </svg>
              <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">¿Confirmas eliminar la propiedad <strong><%= real_state.number %></strong>?</h3>
              <div class='flex justify-between items-center px-15'>
                <%= button_to 'Confirmar', admin_real_state_path(real_state.id), method: :delete, id: "confirm-delete-real-state-#{real_state.number}", class: 'text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center'%>

                <button data-modal-hide="<%= real_state.number %>" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                  Cancelar
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/real_states/edit.html.erb
<div class='input-forms w-full max-w-md mx-auto mt-10'>

  <h1 class='text-3xl mb-5 font-bold items-center'> Editar Propiedad <%= %></h1>
  <%= form_with model: [ :admin, @real_state ] do |form| %>

    <div class="input-devise-container">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'input-devise'%>
    </div>

    <div class="input-devise-container">
      <%= form.label :number %>
      <%= form.number_field :number, class: 'input-devise'%>
    </div>

    <div class="input-devise-container">
      <%= form.label :owner_id %>
      <%= form.select :owner_id, @owners.with_role(:owner).map { |u| [u.email, u.id] }, { include_blank: 'Ninguno' }, class: 'input-devise' %>   
    </div>

    <div class="input-devise-container">
      <%= form.label :tenant_id %>
      <%= form.select :tenant_id, @tenants.with_role(:tenant).map { |u| [u.email, u.id] }, { include_blank: 'Ninguno' }, class: 'input-devise'%>   
    </div>


    <%= form.submit 'crear', id:'save-real-state', class: 'w-full text-white bg-blue-500 hover:bg-blue-800 focus:ring-1 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-outline-none mb-3'%>
  <% end %>

  <% if @real_state.errors.any? %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200 dark:bg-gray-800 dark:text-red-400" role="alert">
      <ul>
        <% @real_state.errors.full_messages.each do |message| %>
          <li class="font-medium"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/admin/real_states/index.html.erb
<h1 class='text-3xl mb-5 font-bold items-center'> <%= t('activerecord.models.real_state.other') %> </h1>
<div class=''> 
  <% if notice %>
    <p class="text-blue-600 mb-3"></p>
    <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
      <strong class="font-medium">Notificación:</strong> <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
      <span class="font-medium">Atención!</span> <%= alert %>
    </div>
  <% end %>
</div>
<div class ='flex justify-between items-center w-full mb-4'>
  <form class="">   
    <label for="real-state-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Buscar</label>
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <input type="search" title="Buscar por nombre o número" name='query' id="real-state-search" class="block p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Número de propiedad" value="<%= params[:query]%>" required />
      <button type="submit" id='button-real-state-search'class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Buscar</button>
    </div>
    <% if params[:query].present? %>
      <a href=<%= admin_real_states_path %> class="font-medium text-red-700 dark:text-red-500 hover:underline dark:hover:text-red-400">Limpiar búsqueda: <%= params[:query] %></a>
    <% end %>
  </form>

  <div class='flex justify-end w-full'>
    <%= link_to 'Crear +', new_admin_real_state_path, class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800', id: 'crate-new-real_state' %>
  </div>
</div>

<div class='w-full mb-4'>
  <%= page_entries_info @real_states %>
</div>

<% if @real_states.any? %>
  <div class='min-w-[280px] sm:w-full grid grid-flow-row grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
    <% @real_states.each do |real_state| %>
      <%= render 'admin/real_states/real_state_card', real_state: real_state %>
    <% end %>
  </div>

  <div class='mt-4' >
    <%= page_entries_info @real_states %>
    <%= paginate @real_states %>
  </div>
<% else %>
  <div class="alert alert-info text-2xl">
    No se encontraron propiedades que coincidan con tu búsqueda.
  </div>
<% end %>
     

app/views/admin/real_states/new.html.erb
<div class='input-forms w-full max-w-md mx-auto mt-10'>

  <h1 class='text-3xl mb-5 font-bold items-center'> Nueva Propiedad </h1> <%t('activerecord.models.real_state.one')%>
  <%= form_with model: [ :admin, @real_state ] do |form| %>

    <div class="input-devise-container">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'input-devise'%>
    </div>

    <div class="input-devise-container">
      <%= form.label :number %>
      <%= form.number_field :number, class: 'input-devise'%>
    </div>

    <div class="input-devise-container">
      <%= form.label :owner_id %>
      <%= form.select :owner_id, @owners.with_role(:owner).map { |u| [u.email, u.id] }, { include_blank: 'Ninguno' }, class: 'input-devise' %>   
    </div>

    <div class="input-devise-container">
      <%= form.label :tenant_id %>
      <%= form.select :tenant_id, @tenants.with_role(:tenant).map { |u| [u.email, u.id] }, { include_blank: 'Ninguno' }, class: 'input-devise'%>   
    </div>


    <%= form.submit 'crear', id:'create-unit', class: 'w-full text-white bg-blue-500 hover:bg-blue-800 focus:ring-1 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-outline-none mb-3'%>
  <% end %>

  <% if @real_state.errors.any? %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200 dark:bg-gray-800 dark:text-red-400" role="alert">
      <ul>
        <% @real_state.errors.full_messages.each do |message| %>
          <li class="font-medium"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/admin/real_states/show.html.erb
<h1 class='text-3xl mb-5 font-bold items-center'> <%= t('frontend.titles.real_states') %> </h1>
<%= render 'layouts/notice_and_alert' %>
<div class='w-full'>
  <div class="p-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700 mb-6"> 
    <p class="text-2xl font-bold text-stone-800 dark:text-white"><%= t('frontend.details.real_state')%></p>

    <p> Número: <%= @real_state.number%> </p>
    <p> Finca: <%= @real_state.address%> </p>
    <p> Propietario: <%= @real_state&.owner&.email%> </p>
    <p> Inquilino: <%= @real_state&.tenant&.email%> </p>
    <div class='flex justify-end items-center'>
      <a href='<%= edit_admin_real_state_path(@real_state) %>' id='edit-real-state-<%=@real_state.number%>' class='px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'>
        <%= t('frontend.buttons.edit') %>
      </a>
    </div>
  </div>
</div>