config/routes.rb
Rails.application.routes.draw do
  resources :real_states, only: [ :index, :show ]

  devise_for :users

  namespace :admin do
    resources :users
    resources :buildings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
      resources :common_rooms, only: [ :new, :create, :show, :edit, :update, :destroy ]
    end
    resources :units, only: [ :new, :create, :show, :edit, :update, :destroy ] # TODO mover al resource building
    resources :real_states, only: [ :new, :create, :index, :show, :edit, :update, :destroy ]
  end



  resources :user_profile, only: [ :show, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'home#home'

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    end

    if user.has_role? :tenant
      can :read, :all, user_id: user # TODO Puede leer lo que sea de el y su edificio
    end

    if user.has_role? :owner
      can :read, RealState, owner: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
  validates :name, :address, :number, presence: true
  validates :number, uniqueness: true
  has_many :units, dependent: :restrict_with_error
  has_many :common_rooms, dependent: :destroy
end

app/models/common_room.rb
class CommonRoom < ApplicationRecord
  belongs_to :building
  validates :name, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :owner, class_name: 'User', optional: true
  belongs_to :tenant,  class_name: 'User', optional: true
  belongs_to :building, optional: true

  validates :number, presence: true
  validates :number, numericality: { only_integer: true }
  validates :tenant, uniqueness: { allow_nil: true }
end

app/models/real_state.rb
class RealState < Property
  after_initialize :set_default_type

  belongs_to :owner, class_name: 'User', optional: true
  belongs_to :tenant, class_name: 'User', optional: true
  default_scope { where(type: 'RealState') }

  validates :address, presence: true
  validate :unique_number_when_building_id_nil

  def unique_number_when_building_id_nil
    return if building_id.present?
  
    if self.class.where(number: number, building_id: nil).where.not(id: id).exists?
      errors.add(:number, I18n.t('activerecord.errors.models.real_state.attribute.number.taken'))
    end
  end
  
  def set_default_type
    self.type ||= 'RealState'
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true


  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/unit.rb
class Unit < Property
  after_initialize :set_default_type

  belongs_to :building
  belongs_to :owner, class_name: 'User', optional: true
  belongs_to :tenant, class_name: 'User', optional: true
  default_scope { where(type: 'Unit') }

  validates :number, uniqueness: { scope: :building_id }

  def set_default_type
    self.type ||= 'Unit'
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties, foreign_key: 'owner_id', dependent: :nullify
  has_one :rented_property, class_name: 'Property', foreign_key: 'tenant_id', dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i[home]

  def home
    @current_user = current_user
  end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end


  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_profile_path
    else
      render :edit
    end
  end
end

app/helpers/admin/buildings_helper.rb
module Admin::BuildingsHelper
end

app/helpers/admin/common_rooms_helper.rb
module Admin::CommonRoomsHelper
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/real_states_helper.rb
module RealStatesHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/layouts/_navbar.html.erb
<%if current_user %>
  <nav id='navbar' class="bg-white border-gray-200 dark:bg-gray-900 shadow-sm dark:shadow-none">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
          <img src="" class="h-8" alt="Ara studio logo" />
          <span class="self-center text-2xl font-semibold whitespace-nowra">Ara Studio</span>
      </a>
      <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
        <button id='user-menu' type="button" class="flex text-sm rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600 cursor-pointer" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
          <span class="sr-only">Open user menu</span>
          <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd"/>
          </svg>
        </button>
        <%= render 'layouts/navbar_menus/user_menu'%>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
      <%= render 'layouts/navbar_menus/navbar_links'%>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/_notice_and_alert.html.erb
<div class=''> 
  <% if notice %>
    <p class="text-blue-600 mb-3"></p>
    <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
      <strong class="font-medium">Notificación:</strong> <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
      <span class="font-medium">Atención!</span> <%= alert %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark:bg-slate-950 min-h-screen text-stone-700 dark:text-white" lang="en">
  <head>
    <title><%= content_for(:title) || "Ara Studio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="theme">
    <%= render 'layouts/navbar' %>
    <main class="container mx-auto my-5 px-5 flex flex-col justify-center items-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/navbar_menus/_navbar_links.html.erb
<ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
  <% if current_user.has_role? :admin%>
    <li>
      <a href="<%= admin_buildings_path %>" class="font-medium text-blue-700 dark:text-white/50 hover:underline dark:hover:text-cyan-300"><%= t('activerecord.models.building.other') %></a>
    </li>
    <li> 
      <%= link_to t('activerecord.models.real_state.other'), admin_real_states_path, class: 'font-medium text-blue-700 dark:text-white/50 hover:underline dark:hover:text-cyan-300' %>
    </li>
    <li> 
      <%= link_to "Usuarios", admin_users_path, class: 'font-medium text-blue-700 dark:text-white/50 hover:underline dark:hover:text-cyan-300' %>
    </li>
  <% end %>
  <li>
    <a href="#" class="font-medium text-blue-700 dark:text-white/50 hover:underline dark:hover:text-cyan-300 line-through">Alquileres</a>
  </li>
  <li>
    <a href="#" class="font-medium text-blue-700 dark:text-white/50 hover:underline dark:hover:text-cyan-300 line-through">Comprobantes</a>
  </li>
</ul>

app/views/layouts/navbar_menus/_user_menu.html.erb
<div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow-sm dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
  <div class="px-4 py-3">
    <span id='user-name'class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
    <span id='user-email' class="block text-sm  text-gray-500 truncate dark:text-gray-400"> <%= current_user.email %></span>
  </div>
  <ul class="py-2" aria-labelledby="user-menu-button">
    <li>
      <button data-action="click->theme#changeTheme" id="theme-toggle" class="block px-4 py-2 text-sm hover:text-stone-700 text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white w-full text-left">
        <svg id='moon' class="w-6 h-6 text-gray-800 dark:text-white hidden" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M11.675 2.015a.998.998 0 0 0-.403.011C6.09 2.4 2 6.722 2 12c0 5.523 4.477 10 10 10 4.356 0 8.058-2.784 9.43-6.667a1 1 0 0 0-1.02-1.33c-.08.006-.105.005-.127.005h-.001l-.028-.002A5.227 5.227 0 0 0 20 14a8 8 0 0 1-8-8c0-.952.121-1.752.404-2.558a.996.996 0 0 0 .096-.428V3a1 1 0 0 0-.825-.985Z" clip-rule="evenodd"/>
        </svg>
        <svg id='sun' class="w-6 h-6 text-gray-800 dark:text-white hidden" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M13 3a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0V3ZM6.343 4.929A1 1 0 0 0 4.93 6.343l1.414 1.414a1 1 0 0 0 1.414-1.414L6.343 4.929Zm12.728 1.414a1 1 0 0 0-1.414-1.414l-1.414 1.414a1 1 0 0 0 1.414 1.414l1.414-1.414ZM12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm-9 4a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2H3Zm16 0a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2h-2ZM7.757 17.657a1 1 0 1 0-1.414-1.414l-1.414 1.414a1 1 0 1 0 1.414 1.414l1.414-1.414Zm9.9-1.414a1 1 0 0 0-1.414 1.414l1.414 1.414a1 1 0 0 0 1.414-1.414l-1.414-1.414ZM13 19a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0v-2Z" clip-rule="evenodd"/>
        </svg>
      </button>
    </li>
    <li>
      <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:text-stone-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white dark:hover:text-white line-through">Dashboard</a>
    </li>
    <li>
      <% unless current_user.has_role? :admin %>
        <a href="<%=  user_profile_path(current_user) %>" class="block px-4 py-2 text-sm text-gray-700 hover:text-stone-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Mis datos</a>
      <% end %>
    </li>
    <li>
      <%= button_to "Salir", destroy_user_session_path, method: :delete, class: 'block px-4 py-2 text-sm text-gray-700 hover:text-stone-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white w-full text-left' %>
    </li>
  </ul>
</div>