config/routes.rb
Rails.application.routes.draw do
  resources :real_states, only: [ :index, :show ]

  devise_for :users

  namespace :admin do
    resources :users
    resources :buildings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
      resources :common_rooms, only: [ :new, :create, :show, :edit, :update, :destroy ]
    end
    resources :units, only: [ :new, :create, :show, :edit, :update, :destroy ] # TODO mover al resource building
    resources :real_states, only: [ :new, :create, :index, :show, :edit, :update, :destroy ]
  end



  resources :user_profile, only: [ :show, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'home#home'

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/building.rb
class Building < ApplicationRecord
  validates :name, :address, :number, presence: true
  validates :number, uniqueness: true
  has_many :units, dependent: :restrict_with_error
  has_many :common_rooms, dependent: :destroy
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def index
    @buildings = building_search_service
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(building_params)

    if @building.save
      redirect_to admin_building_path(@building), notice: "Edificio #{ @building.name } creado correctamente."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    if @building.update(building_params)
      redirect_to admin_buildings_path
    else
      render :edit
    end
  end

  def show
    @building = Building.find(params[:id])
  end

  def destroy
    @building = Building.find(params[:id])

    if @building.destroy
      redirect_to admin_buildings_path
    else
      render :index
    end
  end

  private

  def building_params
    params.require(:building).permit(:number, :name, :address)
  end

  def building_search_service
    Admin::SearchBuildingsService.new(query: params[:query], page: params[:page]).call
  end

  def is_admin?
    unless current_user.has_role? :admin
      redirect_to root_path, alert: 'Acceso denegado.'
    end
  end
end

app/helpers/admin/buildings_helper.rb
module Admin::BuildingsHelper
end

app/views/admin/buildings/_building_card.html.erb
<div class="max-w-sm p-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700">
  <a href="<%= admin_building_path(building.id) %>" class='text-nowrap overflow-hidden'>
      <p id='building-name-<%= building.number %>'class="mb-2 text-2xl font-bold tracking-tight text-stone-700 dark:text-white truncate"><%= building.number %> - <%= building.name %></p>
  </a>

  <p class="truncate mb-3 font-normal text-stone-700 dark:text-stone-400"><%= building.address %></p>

  <div class="flex justify-between items-center">
    <a href="<%= admin_building_path(building.id) %>" id='show-building-<%= building.number %>' class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Ver más
      <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    </a>

    <button data-modal-target="<%= building.number %>" data-modal-toggle="<%= building.number %>" class=" block text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" type="button", id='delete-building-<%= building.number %>-modal'>
      <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
      </svg>
    </button>
  </div>

  <div id="<%= building.number %>" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
      <div class="relative bg-white rounded-lg shadow-sm dark:bg-gray-700">
        <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="<%= building.number %>">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Cerrar modal</span>
        </button>
        <div class="p-4 md:p-5 text-center">
          <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
          </svg>
          <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">¿Confirmas eliminar el edificio <strong><%= building.number %></strong>?</h3>
          <div class='flex justify-between items-center px-15'>
            <%= button_to 'Confirmar', admin_building_path(building.id), method: :delete, id: "confirm-delete-#{building.number}", class: 'text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center'%>

            <button data-modal-hide="<%= building.number %>" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
              Cancelar
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/buildings/index.html.erb
<h1 class='text-3xl mb-5 font-bold items-center'> <%= t('activerecord.models.building.other') %> </h1>
<div class=''> 
  <% if notice %>
    <p class="text-blue-600 mb-3"></p>
    <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
      <strong class="font-medium">Notificación:</strong> <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
      <span class="font-medium">Atención!</span> <%= alert %>
    </div>
  <% end %>
</div>
<div class ='flex justify-between items-center w-full mb-4'>
  <form class="">   
    <label for="building-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Buscar</label>
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <input type="search" title="Buscar por nombre o número" name='query' id="building-search" class="block p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Nombre o Número de edificio" value="<%= params[:query]%>" required />
      <button type="submit" id='button-building-search'class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Buscar</button>
    </div>
    <% if params[:query].present? %>
      <a href=<%= admin_buildings_path %> class="font-medium text-red-700 dark:text-red-500 hover:underline dark:hover:text-red-400">Limpiar búsqueda: <%= params[:query] %></a>
    <% end %>
  </form>

  <div class='flex justify-end w-full'>
    <%= link_to 'Crear +', new_admin_building_path, class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800', id: 'crate-new-building' %>
  </div>
</div>

<div class='w-full mb-4'>
  <%= page_entries_info @buildings %>
</div>

<% if @buildings.any? %>
  <div class='min-w-[280px] sm:w-full grid grid-flow-row grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
    <% @buildings.each do |building| %>
      <%= render 'admin/buildings/building_card', building: building %>
    <% end %>
  </div>

  <div class='mt-4' >
    <%= page_entries_info @buildings %>
    <%= paginate @buildings %>
  </div>
<% else %>
  <div class="alert alert-info text-2xl">
    No se encontraron edificios que coincidan con tu búsqueda.
  </div>
<% end %>
     

app/views/admin/buildings/new.html.erb
<div class='input-forms w-full max-w-md mx-auto mt-10'>

<h1 class='text-3xl mb-5 font-bold items-center'> <%= t('activerecord.models.building.one') %> </h1>
  <%= form_with model: [ :admin, @building ] do |form| %>
    <div class="input-devise-container">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'input-devise' %>
    </div>

    <div class="input-devise-container">
      <%= form.label :number %>
      <%= form.number_field :number, class: 'input-devise'%>
    </div>

    <div class="input-devise-container">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'input-devise' %>
    </div>
    <%= form.submit 'crear', id:'create-building', class: 'w-full text-white bg-blue-500 hover:bg-blue-800 focus:ring-1 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-outline-none mb-3'%>
  <% end %>

  <% if @building.errors.any? %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200 dark:bg-gray-800 dark:text-red-400" role="alert">
      <ul>
        <% @building.errors.full_messages.each do |message| %>
          <li class="font-medium"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/admin/buildings/show.html.erb
<h1 class='text-3xl mb-5 font-bold items-center'> <%= t('frontend.titles.buildings') %> </h1>
<%= render 'layouts/notice_and_alert' %>
<div class='w-full'>
  <div class="p-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700 mb-6"> 
    <p class="text-2xl font-bold text-stone-800 dark:text-white"><%= t('frontend.details.building')%></p>

    <p> Número: <%= @building.number%> </p>
    <p> Nombre: <%= @building.name%> </p>
    <p> Finca: <%= @building.address%> </p>
  </div>
  <!-- TODO: mover a parcial -->
  <div class="p-6 mb-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700"> 
    <div class='md:flex md:justify-between items-center w-full mb-4 border-b-1 border-b-stone-900 dark:border-b-stone-300 pb-4'>
      <p class="mb-4 text-2xl font-bold text-stone-800 dark:text-white"><%= t('frontend.details.building_common_rooms')%></p>
      <div class='w-full md:w-auto flex items-end'>
          <a href='<%= new_admin_building_common_room_path(building_id: @building.id) %>' id='new-common-room-<%=@building.number%>' class='px-3 ml-auto py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800'>
            <%= t('frontend.buttons.add_common_room') %>
          </a>
      </div>
    </div>

    <div class='min-w-[280px] sm:w-full grid grid-flow-row grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
      <%if @building.common_rooms.any? %>
        <% @building.common_rooms.each do |common_room| %>
          <div class='flex flex-col justify-between w-full mb-4 sm:mb-0 p-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700'>
            <div class='mb-4 text-nowrap overflow-hidden'>
              <p class='text-2xl mb-2 font-bold' id="common-room-card-name-<%= common_room.id.gsub!('-', '') %>"><%= common_room.name %></p>
            </div>
            <div class="flex flex-row justify-between items-center">
              <a href="<%= admin_building_common_room_path(building_id: @building.id, id: common_room.id) %>" id='show-common-room-<%= common_room.id %>' class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Ver más
                <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                </svg>
              </a>
            </div>
          </div> 
        <% end %>
      <% else %>
        <p class='text-stone-500'>No hay salas comunes registradas en este edificio.</p>
      <% end %>
    </div>
  </div>
  <!-- TODO: mover a parcial -->

  <!-- TODO: mover a parcial -->
  <div class="p-6 mb-6 bg-white border border-stone-200 rounded-lg shadow-sm dark:bg-gray-900 dark:border-gray-700 "> 
    <div class='md:flex md:justify-between items-center w-full mb-4 border-b-1 border-b-stone-900 dark:border-b-stone-300 pb-4'>
       <p class="mb-4 text-2xl font-bold text-stone-800 dark:text-white"><%= t('frontend.details.building_units')%></p>
       <div class='w-full md:w-auto flex items-end'>
          <a href='<%= new_admin_unit_path(building_id: @building.id) %>' class='px-3 ml-auto py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800'>
            <%= t('frontend.buttons.add_unit') %>
          </a>
       </div>
    </div>
    <div class='min-w-[280px] sm:w-full grid grid-flow-row grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
      <% @building.units.order(:number).each do |unit| %>
        <% owner_email = unit.owner ? unit.owner.email : "No hay propietario" %>
        <% tenant_email = unit.tenant ? unit.tenant.email : "No hay inquilino" %>

        <div class='flex flex-col justify-between w-full mb-4 sm:mb-0 p-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700'>
          <div class='mb-4 text-nowrap overflow-hidden'>
            <p class='text-2xl mb-2 font-bold' id="unit-card-number-<%= unit.number %>"><%= unit.number %></p>
            <p class='font-bold truncate' title='<%= owner_email %>'>Propietario: <%= owner_email %></p></p>
            <p class='font-bold truncate'  title='<%= tenant_email %>'>Inquilino: <%= tenant_email %></p>
          </div>
          <div class="flex flex-row justify-between items-center">
            <a href="<%= admin_unit_path(unit.id) %>" id='show-unit-<%= unit.number %>' class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Ver más
              <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
            </a>
            <button data-modal-target="<%= unit.number %>" data-modal-toggle="<%= unit.number %>" class=" block text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" type="button", id='delete-unit-<%= unit.number %>-modal'>
              <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
              </svg>
            </button>

            <div id="<%= unit.number %>" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                  <div class="relative bg-white rounded-lg shadow-sm dark:bg-gray-700">
                    <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="<%= unit.number %>">
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                      </svg>
                      <span class="sr-only">Cerrar modal</span>
                    </button>
                    <div class="p-4 md:p-5 text-center">
                      <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                      </svg>
                      <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">¿Confirmas eliminar la unidad <strong><%= unit.number %></strong>?</h3>
                      <div class='flex justify-between items-center px-15'>
                        <%= button_to 'Confirmar', admin_unit_path(unit.id), method: :delete, id: "confirm-delete-#{unit.number}", class: 'text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center'%>

                        <button data-modal-hide="<%= unit.number %>" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                          Cancelar
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- TODO: mover a parcial -->
</div>